# Generated by Django 5.2 on 2025-04-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expense'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
    ]
