# Generated by Django 5.2 on 2025-04-22 11:58

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='expense',
            name='category2',
            field=models.ForeignKey(default=main.models.Category.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
