# Generated by Django 5.2 on 2025-04-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_options_expense_category2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
