# Generated by Django 5.2 on 2025-04-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category2',
            new_name='category',
        ),
    ]
