# Generated by Django 5.2 on 2025-04-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_expenselin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='descripcion',
            new_name='description',
        ),
    ]
