# Generated by Django 5.2 on 2025-04-23 15:52

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_descripcion_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('with_totals', django.db.models.manager.Manager()),
            ],
        ),
    ]
