# Generated by Django 5.2 on 2025-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselin',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
