# Generated by Django 5.2 on 2025-04-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselin',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='main.tag'),
        ),
    ]
