# Generated by Django 5.2 on 2025-04-24 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limit')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRAN', 'Transport'), ('ENTR', 'Entertainment'), ('UTIL', 'Utilities'), ('OTHR', 'Other')], max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseLin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.expense', verbose_name='Expense')),
                ('tags', models.ManyToManyField(blank=True, related_name='expense_lines', to='backend.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Expense Line',
                'verbose_name_plural': 'Expense Lines',
                'ordering': ['-date'],
            },
        ),
    ]
