# Generated by Django 5.2 on 2025-04-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration): # type: ignore
    dependencies = [
        ("main", "0001_initial"),
    ]
# Generated by Django 5.2 on 2025-04-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetags',
            name='ExpenseLin',
        ),
        migrations.AlterField(
            model_name='expensetags',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='ExpenseTagLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenselin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_lines', to='mainp.expenselin', verbose_name='Expense Line')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_lines', to='mainp.expensetags', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Expense Tag Line',
                'verbose_name_plural': 'Expense Tag Lines',
            },
        ),
        migrations.AddField(
            model_name='expensetags',
            name='expenselin',
            field=models.ManyToManyField(related_name='tags', through='mainp.ExpenseTagLine', to='mainp.expenselin', verbose_name='Expense Line'),
        ),
    ]
    operations = [
        migrations.CreateModel(
            name="ExpenseLin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Date")),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="main.expense",
                        verbose_name="Expense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Line",
                "verbose_name_plural": "Expense Lines",
            },
        ),
    ]
