# Generated by Django 5.2 on 2025-04-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp', '0002_expenselin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetags',
            name='expenselin',
        ),
        migrations.AddField(
            model_name='expensetags',
            name='expense_lines',
            field=models.ManyToManyField(related_name='tags', to='mainp.expenselin', verbose_name='Expense Line'),
        ),
        migrations.DeleteModel(
            name='ExpenseTagLine',
        ),
    ]