# Generated by Django 5.2 on 2025-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_expense_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
