# Generated by Django 5.2 on 2025-04-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=10, verbose_name='Tag'),
        ),
    ]
