# Generated by Django 5.2 on 2025-04-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_expense_limit'),
        ('main', '0002_expenselin'),
    ]

    operations = [
    ]
