# Generated by Django 5.2 on 2025-04-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expenselin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenselin',
            options={'ordering': ['-date'], 'verbose_name': 'Expense Line', 'verbose_name_plural': 'Expense Lines'},
        ),
    ]
