# Generated by Django 5.2 on 2025-04-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_expenselin_options_expense_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('user', models.CharField(max_length=100, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='expenselin',
            name='tag',
            field=models.ManyToManyField(related_name='lines', to='main.tags', verbose_name='tag'),
        ),
    ]
