# Generated by Django 5.2 on 2025-04-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_expense_options_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='main.expense', verbose_name='Expense')),
            ],
            options={
                'verbose_name': 'ExpenseLin',
                'verbose_name_plural': 'ExpensesLin',
            },
        ),
    ]
