# Generated by Django 5.2 on 2025-04-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselin',
            name='line_tags',
            field=models.ManyToManyField(related_name='tags', to='main.tag', verbose_name='Tags'),
        ),
    ]
