# Generated by Django 5.2 on 2025-04-24 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_expenselin_options_expense_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Name')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('nombre', 'usuario')},
            },
        ),
    ]
