# Generated by Django 5.2 on 2025-04-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expenselin'),
        ('main', '0004_alter_expense_options_alter_expense_category_and_more'),
    ]

    operations = [
    ]
