# Generated by Django 5.2 on 2025-04-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20250423_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expenselin',
            options={'ordering': ['-date'], 'verbose_name': 'Expense Line', 'verbose_name_plural': 'Expense Lines'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRAN', 'Transport'), ('ENTR', 'Entertainment'), ('UTIL', 'Utilities'), ('OTHR', 'Other')], max_length=100, verbose_name='Category'),
        ),
        migrations.AlterModelTable(
            name='expense',
            table=None,
        ),
    ]
