# Generated by Django 5.2 on 2025-04-24 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_etiqueta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etiqueta',
            new_name='Label',
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-date'], 'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.RenameField(
            model_name='label',
            old_name='fecha_creacion',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('name', 'user')},
        ),
        migrations.AddField(
            model_name='expenselin',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='lineas_gasto', to='main.label', verbose_name='Labels'),
        ),
    ]
