# Generated by Django 5.2 on 2025-04-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expenselin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenselin',
            options={'verbose_name': 'Expense Line', 'verbose_name_plural': 'ExpensesLin'},
        ),
    ]
