# Generated by Django 5.2 on 2025-04-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tags_options_alter_expenselin_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselin',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='lines', to='main.tags', verbose_name='tag'),
        ),
    ]
