# Generated by Django 5.2 on 2025-04-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_expensetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.expensetag', verbose_name='ExpenseTag'),
            preserve_default=False,
        ),
    ]
