# Generated by Django 5.2 on 2025-04-23 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_expense_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenselin',
            options={'ordering': ['-date'], 'verbose_name': 'Expense Line', 'verbose_name_plural': 'Expense Lines'},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tag',
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='expenselin',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
