# Generated by Django 5.2 on 2025-04-24 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_expenselin_options_remove_expense_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetag',
            options={'verbose_name': 'ExpenseTag', 'verbose_name_plural': 'ExpenseTags'},
        ),
        migrations.CreateModel(
            name='ExpenseLinTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.expenselin')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.expensetag')),
            ],
            options={
                'unique_together': {('expense_line', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='expenselin',
            name='tags',
            field=models.ManyToManyField(related_name='expense_lines', through='main.ExpenseLinTag', to='main.expensetag', verbose_name='Tags'),
        ),
    ]
