# Generated by Django 5.2 on 2025-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_expenselin_options_remove_expense_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselin',
            name='tag',
            field=models.ManyToManyField(to='main.expensetag'),
        ),
    ]
