# Generated by Django 5.2 on 2025-04-24 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_expensetag_options_expenselintag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenselin',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='expensetag',
            options={'verbose_name': 'ExpenseTag', 'verbose_name_plural': 'ExpensesTag'},
        ),
        migrations.AddField(
            model_name='expenselin',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='lines', to='main.expensetag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='expensetag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses_tag', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='ExpenseLinTag',
        ),
    ]
