# Generated by Django 5.2 on 2025-04-24 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_expenselin_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselin',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='main.expensetag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='expensetag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses_tag', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
