# Generated by Django 5.2 on 2025-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_expensetag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselin',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='main.expensetag', verbose_name='Tag'),
        ),
    ]
