# Generated by Django 5.2 on 2025-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('description', models.CharField(max_length=255)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRANS', 'Transport'), ('ENTR', 'Entretainment'), ('UTIL', 'Utilities'), ('OTHR', 'Other')], max_length=100)),
            ],
        ),
    ]
