# Generated by Django 5.2 on 2025-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
