# Generated by Django 5.2 on 2025-04-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetags',
            name='ExpenseLin',
        ),
        migrations.AlterField(
            model_name='expensetags',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='ExpenseTagLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenselin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_lines', to='mainp.expenselin', verbose_name='Expense Line')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_lines', to='mainp.expensetags', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Expense Tag Line',
                'verbose_name_plural': 'Expense Tag Lines',
            },
        ),
        migrations.AddField(
            model_name='expensetags',
            name='expenselin',
            field=models.ManyToManyField(related_name='tags', through='mainp.ExpenseTagLine', to='mainp.expenselin', verbose_name='Expense Line'),
        ),
    ]
