# Generated by Django 5.2 on 2025-04-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainp', '0003_alter_expense_options_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseLin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
